### PR TITLE
Fix build to work with Rails 6.1

### PR DESCRIPTION
**Pull request by pablobm**
Currently all PRs are getting a failed build with the following error:

```
rake aborted!
NoMethodError: undefined method `hour' for 1:Integer
/home/circleci/administrate-field-nested_has_many/spec/dummy/config/environments/test.rb:18:in `block in <top (required)>'
```

This suggests that ActiveSupport is not loading correctly, or at least its integer-time extensions are not being loaded.

After some research, this appears to be a problem brought by Rails 6.1. The default `Gemfile.lock` of this app is not checked into source control, so it's generated anew every time that the build runs. As soon as Rails 6.1 was out, the build started using it, and specs started failing.

To fix this, I created a new Rails engine separately, using Rails 6.1. Then I copied across the files of the default dummy app. This gives bring roughly these changes that can be seen in the PR.

My theory the integer-time extensions not being loaded is validated by how the new environment files include a explicit `require "active_support/core_ext/integer/time"`. Perhaps I could have added just that and left it at that, but I thought I may as well update everything else.

Having said that, there are two things I haven't updated. First, I haven't converted the app to use Webpacker for the JS assets. The dummy app will still use Sprockets (I think that's it, right? I can't remember the detail of how the asset pipeline has evolved in the last few years).

Second, I have removed several unused frameworks: active_storage, action_mailer, and action_cable. Some were already unused, and in fact having them broke things because this gem doesn't have a direct dependency on Rails. Instead we depend on rspec-rails which in turn only depends on some specific frameworks. So either I added Rails as a dependency, or I removed frameworks. I went for the latter option, and in fact I have removed more than strictly necessary.

Once this (or an alternative) is merged, other PRs should be green again.

### CODE REVIEW

**Comment by pablobm** [comment]
Why oh why is the build not running now... It was running this morning!

**Comment by nickcharlton** [comment]
> The dummy app will still use Sprockets (I think that's it, right? I can't remember the detail of how the asset pipeline has evolved in the last few years).

**Comment by nickcharlton** [comment]
> The dummy app will still use Sprockets (I think that's it, right? I can't remember the detail of how the asset pipeline has evolved in the last few years).

I do believe this is true!

**Review by nickcharlton — APPROVED** [review]
I tried this out locally, so I'm confident to merge it.
